import pandas as pd
import numpy as np
import shutil
import os
from PIL import Image


def move_files(csv_path, base_path, destination_path, numpy_arrays):
    # Read the CSV file
    df = pd.read_csv(csv_path)

    # Iterate over the rows of the DataFrame
    for index, row in df.iterrows():
        # Check if the row (excluding the first column) matches any numpy array

        for i, arr in enumerate(numpy_arrays):
            if np.all(np.array(row.values[1:]) == arr):

                file_index = row.values[0]
                file_path = os.path.join(
                    base_path, str(file_index) + ".png"
                )  # Construct file path
                print(f"Moving_file {file_path}")
                # Move the file to the destination folder
                out = os.path.join(destination_path, str(i), str(index) + ".png")
                if os.path.exists(os.path.join(destination_path, str(i))) == False:
                    os.mkdir(os.path.join(destination_path, str(i)))
                    # with Image.open(file_path) as img:
                    #     img = img.resize((1024, 1024), Image.ANTIALIAS)
                    #     img.save(out)
                shutil.copy(file_path, out)


# Example usage
csv_file_path = "/projects/NEI/pranay/Eyes/Datasets/A. RFMiD_All_Classes_Dataset/2. Groundtruths/c. RFMiD_Testing_Labels_mod.csv"  # Path to your CSV file
base_path = "/projects/NEI/pranay/Eyes/Datasets/A. RFMiD_All_Classes_Dataset/1. Original Images Processed 5/c. Testing Set"  # Base path where the files are located
destination_path = "/projects/NEI/pranay/Eyes/Datasets/Final_experiment_fundus/Original"  # Destination folder path

# Replace these with your numpy arrays
numpy_arrays = [
    np.array(
        [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
        ]
    ),  # Your first numpy array
    np.array(
        [
            1,
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
        ]
    ),
    np.array(
        [
            1,
            0,
            0,
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
        ]
    ),
    np.array(
        [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
        ]
    ),
    np.array(
        [
            1,
            0,
            0,
            0,
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
        ]
    ),  # Your second numpy array,
    np.array(
        [
            1,
            0,
            0,
            0,
            0,
            0,
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
        ]
    ),
    np.array(
        [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
        ]
    )
    # np.array([1,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
    #     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
    #     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])
    # Add more arrays as needed
]

# Call the function
move_files(csv_file_path, base_path, destination_path, numpy_arrays)
